# Generated by Django 4.1.3 on 2022-11-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=290)),
                ('release_date', models.CharField(max_length=290)),
                ('poster_path', models.CharField(max_length=590)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
