# Generated by Django 4.1.3 on 2022-11-22 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=590),
            preserve_default=False,
        ),
    ]
