# Generated by Django 4.1.3 on 2022-11-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
